In [1]:
import numpy as np


In [3]:
list_a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
list_a


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [83]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a.ndim


2

In [26]:
a.shape


(3, 4)

In [27]:
np.array(list_a[1])


array([5, 6, 7, 8])

In [31]:
a[2].shape


(4,)

In [54]:
# np.array([1, 2, 3])
# np.zeros((2,5))
# np.ones((6, 2))
# np.empty(5)
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
list


Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [62]:
ar3d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[1,2,3,4]]])
ar3d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 1,  2,  3,  4]]])

In [63]:
ar3d.ndim


3

In [64]:
ar3d.shape


(2, 2, 4)

In [82]:
ar3d.size


16

In [77]:
a = np.array([1,3,2,4])
a


array([1, 3, 2, 4])

In [80]:
help(np.sort)


Help on _ArrayFunctionDispatcher in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second,

In [79]:
# np.append(a, 5)
# np.delete(a, 1)
np.sort(a)


array([1, 2, 3, 4])

In [81]:
list


1

In [84]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a.shape


(3, 4)

In [86]:
np.reshape(a, (4 ,3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
a.reshape((4 ,3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
a.reshape((2 ,6))


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [96]:
a.reshape(1, 12)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [103]:
a.reshape(12, 1)


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [98]:
a.reshape(-1,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
a.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
a.shape


(3, 4)

In [111]:
a[np.newaxis]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [108]:
a[np.newaxis].shape


(1, 3, 4)

In [112]:
a[:, np.newaxis]


array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [113]:
a[:, np.newaxis].shape


(3, 1, 4)

In [114]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
names = np.array(["aldo", "aldi", "alda", 5])
names


array(['aldo', 'aldi', 'alda', '5'], dtype='<U21')

In [150]:
names[names == 'alda']


array(['alda'], dtype='<U21')

In [151]:
names[names > 3]


UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.Int64DType'>) -> <class 'numpy.dtypes.BoolDType'>

In [120]:
a[a > 4]


array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
a[a < 10]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
a[(a < 4) | (a > 6)]


array([ 1,  2,  3,  7,  8,  9, 10, 11, 12])

In [152]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
arr1 = arr[3:8]
arr1


In [154]:
a_1 = np.array([[1, 1],
     [2, 2]])

a_2 = np.array([[3, 3],
     [4, 4]])


In [155]:
# vstack
print(a_1)
print(a_2)


[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [157]:
np.vstack([a_1, a_2])


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [158]:
np.hstack((a_1, a_2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [161]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [170]:
np.hsplit(arrsplit, 3)


[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [176]:
a_reshaped = a.reshape(4, 3)
a_reshaped


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [183]:
np.vsplit(a_reshaped, 2)


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [192]:
b = {"key1": "val1", "key2": "val2", "key3": "val3"}
b


{'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}

In [190]:
list_a


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [195]:
a[0]


array([1, 2, 3, 4])

In [196]:
a[1]


array([5, 6, 7, 8])

In [197]:
a[0] + a[1]


array([ 6,  8, 10, 12])

In [200]:
list_a[0] + list_a[1]


[1, 2, 3, 4, 5, 6, 7, 8]

In [204]:
a[0]


array([1, 2, 3, 4])

In [206]:
a[0].shape


(4,)

In [218]:
a[0] * a[1]


array([ 5, 12, 21, 32])

In [219]:
np.sum(a[0] * a[1])


70

In [220]:
a[0] @ a[1]


70

In [212]:
a_reshaped_0 = a[0].reshape(4, 1)
a_reshaped_0


array([[1],
       [2],
       [3],
       [4]])

In [215]:
a_reshaped_1 = a[1].reshape(1, 4)
a_reshaped_1


array([[5, 6, 7, 8]])

In [216]:
a_reshaped_0 @ a_reshaped_1


array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [221]:
a_reshaped_1 @ a_reshaped_0


array([[70]])

In [205]:
a[1]


array([5, 6, 7, 8])

In [207]:
a[1].shape


(4,)

In [203]:
a[1][:3]


array([5, 6, 7])

In [202]:
a[0] + a[1][:3]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [208]:
a[0] * a[1]


array([ 5, 12, 21, 32])

In [209]:
a[0] @ a[1]


70

In [222]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [224]:
list_a


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [226]:
list_a[0][1]


2

In [227]:
a[0][1]


2

In [228]:
a[0, 1]


2

In [229]:
a.max()


12

In [230]:
a.min()


1

In [235]:
a.transpose()


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [239]:
a.T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])